#! /bin/sh
################################################################################
#
#	Load driver for Texas Instruments ADS1672 Analog to Digital Converter.
#
#	Copyright (C) 2011-2013 Paul Barker, Loughborough University
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
################################################################################

set -e

# Variables
MODULE_NAME="ads1672"
DEVICE_NAME=$MODULE_NAME
DEVICE_OWNER="root"
DEVICE_GROUP="root"
DEVICE_MODE="0660"

# Invoke modprobe with the arguments we got on the command line
modprobe $MODULE_NAME $@

# Remove stale device node (if present) and create a fresh node with the correct
# major and minor numbers
rm -f /dev/$DEVICE_NAME

DEVICE_MAJOR=$(cat /sys/module/$MODULE_NAME/parameters/major)
DEVICE_MINOR=$(cat /sys/module/$MODULE_NAME/parameters/minor)

mknod /dev/$DEVICE_NAME c $DEVICE_MAJOR $DEVICE_MINOR

# Set user, group and mode
chown $DEVICE_OWNER /dev/$DEVICE_NAME
chgrp $DEVICE_GROUP /dev/$DEVICE_NAME
chmod $DEVICE_MODE /dev/$DEVICE_NAME
